# Generated by Django 5.2.7 on 2025-11-03 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poemHub', '0002_poem_country_poem_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrycurrency',
            name='currency_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='code',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=20),
        ),
    ]
