# Generated by Django 5.2.7 on 2025-11-03 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poemHub', '0003_alter_countrycurrency_currency_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='poem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='poemHub.poem'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='poemHub.comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='poem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='poemHub.poem'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='poem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='poemHub.poem'),
        ),
        migrations.AlterField(
            model_name='image',
            name='poem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='poemHub.poem'),
        ),
        migrations.AlterField(
            model_name='like',
            name='poem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='poemHub.poem'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='poem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='poemHub.poem'),
        ),
        migrations.AlterField(
            model_name='poemtag',
            name='poem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poem_tags', to='poemHub.poem'),
        ),
        migrations.AlterField(
            model_name='poemtag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_poems', to='poemHub.tag'),
        ),
    ]
